version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  traefik:
    image: traefik:1.7.12
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik/traefik.toml}:/traefik.toml
      - ${ACME_JSON:-./traefik/acme.json}:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - ${TRAEFIK_URL_CONFIG:-traefik.frontend.rule=Host:traefik.docker.localhost}
      - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt
    logging: *default-logging

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      # so support single node development
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-elasticsearch"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=9200"
      - ${ELASTICSEARCH_URL_CONFIG:-traefik.frontend.rule=Host:elasticsearch.docker.localhost}
      - ${ELASTICSEARCH_AUTH:-traefik.frontend.auth.basic=kibana:$apr1$.lcgllId$9sUY3fPk/gDuh3NQ55024/}
    logging: *default-logging

  curator:
    image: bobrik/curator:5.7.6
    environment:
      UNIT_COUNT: ${CURATOR_UNIT_COUNT}
      UNIT: ${CURATOR_UNIT}
      ES_HOST: ${CURATOR_ES_HOST}
    volumes:
      - ./curator/action-file.yml:/action-file.yml
      - ./curator/config.yml:/config.yml
    depends_on:
      - elasticsearch

  logstash:
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/${LOGSTASH_PATH_CONFIG}:/usr/share/logstash/pipeline
      - ${LOGSTASH_PATH_LOGS}:/mnt/log:rw
    ports:
      - "5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default
    depends_on:
      - elasticsearch
    logging: *default-logging

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    expose:
      - "5601"
    ports:
      - "5601:5601"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-kibana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=5601"
      - ${KIBANA_URL_CONFIG:-traefik.frontend.rule=Host:kibana.docker.localhost}
      - ${KIBANA_AUTH:-traefik.frontend.auth.basic=kibana:$apr1$.lcgllId$9sUY3fPk/gDuh3NQ55024/}
    logging: *default-logging

  grafana:
    image: grafana/grafana:6.2.5
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS:-secret}
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-grafana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:grafana.docker.localhost}
    logging: *default-logging

  rsyslog:
    build: ./rsyslog
#    network_mode: "host"
    ports:
      - 514:514/udp
      - 514:514
    volumes:
      - ./rsyslog/${RSYSLOG_CONF}:/etc/rsyslogd.conf
      - rsyslog_data:/var/log
    logging: *default-logging

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.2.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d
      - ./filebeat/module:/usr/share/filebeat/module
      - ./filebeat/template:/template
      - ${BASE_PATH:-/data}/filebeat:/log
    command: -e -strict.perms=false
    networks:
      - default
    logging: *default-logging

networks:
  web:
    external: true

volumes:
  elasticsearch_data:
  grafana_data:
  rsyslog_data:
